image: ghcr.io/rocker-org/devcontainer/geospatial:4

tasks:
  - name: Minor config for R to work in cloud dev env's
    command: .devcontainer/scripts/post-create-command.sh 

vscode:
  extensions:
    - quarto.quarto
    - REditorSupport.r
    - bierner.markdown-preview-github-styles
