image: gitpod/workspace-base

tasks:
  - name: Set-up R, apptainer
    command: |
        ./scripts/setup/post_create_command.sh 

vscode:
  extensions:
    - quarto.quarto
    - REditorSupport.r
    - bierner.markdown-preview-github-styles
